"""remove description

Revision ID: f1bc91d5486e
Revises: 1a1ae61ffbde
Create Date: 2024-04-04 23:32:58.709598

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bc91d5486e'
down_revision: Union[str, None] = '1a1ae61ffbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###
